name: CI
on:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: tuqulore/.github/setup@862223e87aebb86ee0e7e2db495d65dc441b31df # main
      - run: pnpm lint
      - run: pnpm -r test
      - uses: tuqulore/.github/format@862223e87aebb86ee0e7e2db495d65dc441b31df # main
