name: CI
on:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: tuqulore/.github/setup@11aae4eb6384c34e47e7ab530576d416ec9ff007 # main
      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm -r test
      - run: pnpm test:types
      - uses: tuqulore/.github/format@11aae4eb6384c34e47e7ab530576d416ec9ff007 # main
