name: Release
on:
  workflow_dispatch:
    inputs:
      semver:
        description: next semantic version(s) value
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
          - prerelease
          - prepatch
          - preminor
          - premajor
jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: tuqulore/.github/setup@main
      - run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git branch --move release
          git push -f origin release
          pnpm versionup ${{ github.event.inputs.semver }} --yes
          git commit --all --message "chore(release): v$(cat lerna.json | jq -r .version)"
          git push origin release
          gh pr create --fill
        env:
          GH_TOKEN: ${{ github.token }}
      - if: ${{ failure() }}
        run: git push origin :release
