name: Release
on:
  workflow_dispatch:
    inputs:
      semver:
        description: next semantic version(s) value
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm

      - run: pnpm install

      - name: Configure git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create release branch and bump version
        run: |
          git checkout -b release
          pnpm versionup ${{ inputs.semver }} --yes --no-git-tag-version
          git push -f origin release
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Create pull request
        run: |
          VERSION=$(cat lerna.json | jq -r .version)
          gh pr create \
            --base main \
            --title "chore(release): v${VERSION}" \
            --body "Release v${VERSION}"
        env:
          GH_TOKEN: ${{ github.token }}

      - if: failure()
        run: git push origin :release
